# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Push the Docker image

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Docker image
      run: docker build -t titanscout2022/red-alliance-api:latest .
    - name: Log into the GitHub Docker Registry
      env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
    - name: docker push
      run: docker push titanscout2022/red-alliance-api:latest
